import type { QuizQuestion } from "@/lib/types";
import { Rng } from "@/lib/data/rng";

export const QUESTIONS: QuizQuestion[] = [
  // Pillar 1 — The Science of Restaurant Sales
  {
    id: "q-p1-1",
    pillarId: "p1",
    type: "mcq",
    prompt: "What is the correct formula for Average Transaction Value (ATV)?",
    options: [
      "Total Sales ÷ Number of Transactions",
      "Total Items Sold ÷ Number of Guests",
      "Number of Transactions ÷ Total Sales",
      "Total Sales ÷ Number of Employees",
    ],
    correctAnswer: "Total Sales ÷ Number of Transactions",
    explanation: "ATV measures how much, on average, each transaction is worth — Total Sales divided by Number of Transactions.",
    difficulty: "foundation",
  },
  {
    id: "q-p1-2",
    pillarId: "p1",
    type: "true-false",
    prompt: "Items Per Transaction (IPT) is one of the strongest predictors of ATV.",
    correctAnswer: "true",
    explanation: "Each additional relevant item added to an order compounds the check total, making IPT a strong ATV driver.",
    difficulty: "foundation",
  },
  {
    id: "q-p1-3",
    pillarId: "p1",
    type: "matching",
    prompt: "Match each Menu Engineering quadrant to its definition.",
    options: [
      "Stars = High popularity, high profit",
      "Plow-Horses = High popularity, low profit",
      "Puzzles = Low popularity, high profit",
      "Dogs = Low popularity, low profit",
    ],
    correctAnswer: [
      "Stars = High popularity, high profit",
      "Plow-Horses = High popularity, low profit",
      "Puzzles = Low popularity, high profit",
      "Dogs = Low popularity, low profit",
    ],
    explanation: "The Menu Engineering matrix classifies items by popularity and profitability to guide what staff should recommend.",
    difficulty: "intermediate",
  },
  {
    id: "q-p1-4",
    pillarId: "p1",
    type: "scenario",
    prompt: "A guest orders a Plow-Horse item (popular but low margin). What is the best sales response?",
    options: [
      "Say nothing further and move on",
      "Pair it with a high-margin Puzzle item recommendation",
      "Talk them out of the item entirely",
      "Offer a discount to encourage a bigger order",
    ],
    correctAnswer: "Pair it with a high-margin Puzzle item recommendation",
    explanation: "Pairing a Plow-Horse with a Puzzle item raises the check's overall profitability without discouraging the guest's choice.",
    difficulty: "intermediate",
  },
  {
    id: "q-p1-5",
    pillarId: "p1",
    type: "mcq",
    prompt: "Which lever in the Restaurant Sales Equation (Guests × ATV × Frequency) does a server influence most directly, every shift?",
    options: ["Guests", "ATV", "Frequency", "None of these"],
    correctAnswer: "ATV",
    explanation: "Guest count is mostly driven by marketing and location; ATV is directly influenced by staff behavior on every single order.",
    difficulty: "foundation",
  },
  {
    id: "q-p1-6",
    pillarId: "p1",
    type: "image",
    prompt: "In the Menu Engineering matrix diagram, which quadrant sits in the top-right (high popularity, high profit)?",
    options: ["Stars", "Plow-Horses", "Puzzles", "Dogs"],
    correctAnswer: "Stars",
    explanation: "Stars occupy the top-right of the matrix — these should always be mentioned first.",
    difficulty: "foundation",
  },

  // Pillar 2 — The Psychology of Buying
  {
    id: "q-p2-1",
    pillarId: "p2",
    type: "ordering",
    prompt: "Put the stages of the Guest Journey in the correct order.",
    options: ["Arrival", "Seated", "Ordering", "Service", "Payment", "Departure"],
    correctAnswer: ["Arrival", "Seated", "Ordering", "Service", "Payment", "Departure"],
    explanation: "The Guest Journey moves from Arrival through Departure — each stage carries a different sales opportunity.",
    difficulty: "foundation",
  },
  {
    id: "q-p2-2",
    pillarId: "p2",
    type: "mcq",
    prompt: "What is 'anchoring' in the context of guest psychology?",
    options: [
      "Offering a discount to close a sale",
      "The first option mentioned becomes the reference point for comparison",
      "Repeating the guest's order back to them",
      "Only suggesting the cheapest item",
    ],
    correctAnswer: "The first option mentioned becomes the reference point for comparison",
    explanation: "Anchoring means the first suggestion shapes how guests judge every option that follows.",
    difficulty: "intermediate",
  },
  {
    id: "q-p2-3",
    pillarId: "p2",
    type: "true-false",
    prompt: "It's acceptable to exaggerate an item's popularity to create social proof, as long as it increases sales.",
    correctAnswer: "false",
    explanation: "Fabricated social proof or scarcity damages guest trust and is explicitly against Kükie Academy's hospitality-first approach.",
    difficulty: "foundation",
  },
  {
    id: "q-p2-4",
    pillarId: "p2",
    type: "scenario",
    prompt: "A guest is scanning the menu quickly and glancing at their watch. What's the best read and response?",
    options: [
      "They are time-pressured — offer an efficient, specific recommendation",
      "They are uninterested in the menu — leave them alone",
      "They want the most expensive option — recommend premium only",
      "They are undecided — ask no questions and wait",
    ],
    correctAnswer: "They are time-pressured — offer an efficient, specific recommendation",
    explanation: "Reading pace and body language lets you tailor the recommendation style to what the guest actually needs.",
    difficulty: "intermediate",
  },
  {
    id: "q-p2-5",
    pillarId: "p2",
    type: "mcq",
    prompt: "According to Kükie Academy guest survey data, what check-average lift is associated with guests who feel a genuine connection with their server?",
    options: ["5%", "12%", "23%", "40%"],
    correctAnswer: "23%",
    explanation: "Guests who report a genuine connection show a 23% higher check average on average.",
    difficulty: "intermediate",
  },
  {
    id: "q-p2-6",
    pillarId: "p2",
    type: "true-false",
    prompt: "Guests generally prefer a wide-open, unguided choice over a confident, specific recommendation.",
    correctAnswer: "false",
    explanation: "Decision fatigue means too many open options creates hesitation — guests generally prefer being guided.",
    difficulty: "foundation",
  },

  // Pillar 3 — Sales Through Hospitality
  {
    id: "q-p3-1",
    pillarId: "p3",
    type: "ordering",
    prompt: "Put the steps of the objection-handling framework in the correct order.",
    options: ["Acknowledge", "Ask", "Advise", "Affirm"],
    correctAnswer: ["Acknowledge", "Ask", "Advise", "Affirm"],
    explanation: "The 4 A's — Acknowledge, Ask, Advise, Affirm — is the standard Kükie Academy objection-handling sequence.",
    difficulty: "foundation",
  },
  {
    id: "q-p3-2",
    pillarId: "p3",
    type: "mcq",
    prompt: "Which phrase best reflects the 'language of suggestion' rather than the 'language of the order-taker'?",
    options: [
      "'Anything else?'",
      "'Is that everything?'",
      "'Our warm chocolate lava cake is made fresh — would you like me to bring one out for the table?'",
      "'You want dessert?'",
    ],
    correctAnswer: "'Our warm chocolate lava cake is made fresh — would you like me to bring one out for the table?'",
    explanation: "Specific, sensory, and easy to say yes to — this is the language of suggestion in action.",
    difficulty: "foundation",
  },
  {
    id: "q-p3-3",
    pillarId: "p3",
    type: "scenario",
    prompt: "A guest says 'that's a bit pricey for me.' What is the correct first response under the 4 A's framework?",
    options: [
      "Immediately offer a discount",
      "Acknowledge the concern without arguing",
      "Ignore the comment and repeat the recommendation",
      "Ask them to choose from the cheapest section of the menu",
    ],
    correctAnswer: "Acknowledge the concern without arguing",
    explanation: "The first step is always to Acknowledge — validate the guest's concern before asking a clarifying question.",
    difficulty: "intermediate",
  },
  {
    id: "q-p3-4",
    pillarId: "p3",
    type: "true-false",
    prompt: "The goal of sales-through-hospitality is to sell guests something they don't actually want.",
    correctAnswer: "false",
    explanation: "The goal is to make sure guests don't miss something they would have loved — never to push an unwanted item.",
    difficulty: "foundation",
  },
  {
    id: "q-p3-5",
    pillarId: "p3",
    type: "mcq",
    prompt: "What carries more weight than word choice when delivering a recommendation, according to Pillar 3?",
    options: ["Menu placement", "Tone, pace and eye contact", "The exact script used", "How fast the words are spoken"],
    correctAnswer: "Tone, pace and eye contact",
    explanation: "Delivery — tone, pace, eye contact — determines whether a recommendation feels like hospitality or a pitch.",
    difficulty: "intermediate",
  },
  {
    id: "q-p3-6",
    pillarId: "p3",
    type: "scenario",
    prompt: "A guest declines a starter, saying they're 'not that hungry.' What is the best follow-up?",
    options: [
      "Drop the subject entirely and never revisit it",
      "Insist they order it anyway",
      "Leave the door open: 'Happy to add it anytime before your main arrives'",
      "Offer it for free",
    ],
    correctAnswer: "Leave the door open: 'Happy to add it anytime before your main arrives'",
    explanation: "A soft, no-pressure offer that leaves the door open often converts a few minutes later.",
    difficulty: "intermediate",
  },

  // Pillar 4 — Advanced Selling Techniques
  {
    id: "q-p4-1",
    pillarId: "p4",
    type: "ordering",
    prompt: "Put the suggestive selling script framework in the correct order.",
    options: ["Name", "Describe", "Invite"],
    correctAnswer: ["Name", "Describe", "Invite"],
    explanation: "Name the item, describe one sensory detail, then invite the guest to add it.",
    difficulty: "foundation",
  },
  {
    id: "q-p4-2",
    pillarId: "p4",
    type: "matching",
    prompt: "Match each technique to its correct definition.",
    options: [
      "Upselling = Guiding toward a larger or more premium version of the same item",
      "Cross-Selling = Recommending a complementary item from a different category",
      "Premium Selling = Leading with the best version of an experience",
      "Suggestive Selling = Offering an item the guest hadn't thought to order",
    ],
    correctAnswer: [
      "Upselling = Guiding toward a larger or more premium version of the same item",
      "Cross-Selling = Recommending a complementary item from a different category",
      "Premium Selling = Leading with the best version of an experience",
      "Suggestive Selling = Offering an item the guest hadn't thought to order",
    ],
    explanation: "Each technique targets a different moment and mechanism in the sale.",
    difficulty: "intermediate",
  },
  {
    id: "q-p4-3",
    pillarId: "p4",
    type: "mcq",
    prompt: "When is beverage attachment most effective?",
    options: [
      "After the food has already arrived",
      "At the moment the order is taken",
      "Only at the end of the meal",
      "Never — it should not be suggested",
    ],
    correctAnswer: "At the moment the order is taken",
    explanation: "Cross-selling and attachment are most effective at order time, not after food has already arrived.",
    difficulty: "foundation",
  },
  {
    id: "q-p4-4",
    pillarId: "p4",
    type: "true-false",
    prompt: "Upselling works well because the guest has already committed to the category, so you're refining rather than redirecting.",
    correctAnswer: "true",
    explanation: "Because the guest already chose the category, refining to a premium version is low-friction.",
    difficulty: "foundation",
  },
  {
    id: "q-p4-5",
    pillarId: "p4",
    type: "scenario",
    prompt: "A guest orders a classic burger with nothing else. What is the strongest technique stack to apply next?",
    options: [
      "Say nothing and place the order",
      "Suggest fries (cross-sell), a drink (attachment), and plant a dessert seed for later",
      "Only suggest the most expensive item on the menu",
      "Ask if they want to change their order",
    ],
    correctAnswer: "Suggest fries (cross-sell), a drink (attachment), and plant a dessert seed for later",
    explanation: "This mirrors the full technique stack scenario from Pillar 4 — multiple light-touch suggestions in one interaction.",
    difficulty: "advanced",
  },
  {
    id: "q-p4-6",
    pillarId: "p4",
    type: "mcq",
    prompt: "How many suggestions should typically be stacked in one breath, according to Pillar 4?",
    options: ["As many as possible", "2-3 maximum", "Exactly 5", "Only 1, ever"],
    correctAnswer: "2-3 maximum",
    explanation: "Stacking more than 2-3 suggestions at once tends to overwhelm the guest.",
    difficulty: "intermediate",
  },

  // Pillar 5 — Operational Execution
  {
    id: "q-p5-1",
    pillarId: "p5",
    type: "ordering",
    prompt: "Put the Daily Floor Routine in the correct order.",
    options: ["Pre-Shift Huddle", "Peak Execution", "Post-Shift Debrief"],
    correctAnswer: ["Pre-Shift Huddle", "Peak Execution", "Post-Shift Debrief"],
    explanation: "The routine starts with a huddle, moves through execution with real-time coaching, and closes with a debrief.",
    difficulty: "foundation",
  },
  {
    id: "q-p5-2",
    pillarId: "p5",
    type: "true-false",
    prompt: "The best coaching happens days later during a formal review, not in the moment.",
    correctAnswer: "false",
    explanation: "In-the-moment coaching, within minutes of the interaction, builds habits faster than delayed feedback.",
    difficulty: "foundation",
  },
  {
    id: "q-p5-3",
    pillarId: "p5",
    type: "mcq",
    prompt: "Which framework is recommended for in-the-moment coaching conversations?",
    options: ["SWOT", "The 4 A's (Acknowledge, Ask, Advise, Affirm)", "SMART Goals", "PDCA"],
    correctAnswer: "The 4 A's (Acknowledge, Ask, Advise, Affirm)",
    explanation: "The same 4 A's framework used for guest objections applies well to coaching conversations.",
    difficulty: "intermediate",
  },
  {
    id: "q-p5-4",
    pillarId: "p5",
    type: "scenario",
    prompt: "In the Role Play scenario, a guest declines a suggestion warmly and the team member says 'No problem at all, I'll get that started right away.' How should this be scored?",
    options: [
      "A fail — the guest didn't buy anything",
      "A pass — graceful, zero-pressure handling of a decline",
      "Incomplete — needs a second attempt",
      "A fail — should have pushed harder",
    ],
    correctAnswer: "A pass — graceful, zero-pressure handling of a decline",
    explanation: "A warm, no-pressure response to a decline reflects the hospitality-first standard, even without a sale.",
    difficulty: "advanced",
  },
  {
    id: "q-p5-5",
    pillarId: "p5",
    type: "matching",
    prompt: "Match each Practical Assessment category to its focus area.",
    options: [
      "Greeting, Smile, Eye Contact = Hospitality fundamentals",
      "Menu Knowledge, Confidence = Technique internalization",
      "Upselling, Cross-Selling, Closing = Applied sales behavior",
      "Guest Engagement, Professionalism = Overall impression",
    ],
    correctAnswer: [
      "Greeting, Smile, Eye Contact = Hospitality fundamentals",
      "Menu Knowledge, Confidence = Technique internalization",
      "Upselling, Cross-Selling, Closing = Applied sales behavior",
      "Guest Engagement, Professionalism = Overall impression",
    ],
    explanation: "The Practical Assessment rubric groups criteria into these four focus areas.",
    difficulty: "intermediate",
  },

  // Pillar 6 — Measuring Success
  {
    id: "q-p6-1",
    pillarId: "p6",
    type: "mcq",
    prompt: "What is the pass mark for the Knowledge Test?",
    options: ["60%", "70%", "80%", "90%"],
    correctAnswer: "80%",
    explanation: "The Kükie Academy Knowledge Test requires an 80% pass mark.",
    difficulty: "foundation",
  },
  {
    id: "q-p6-2",
    pillarId: "p6",
    type: "true-false",
    prompt: "Certification is the finish line of the training journey.",
    correctAnswer: "false",
    explanation: "Certification is a milestone, not a finish line — Manager Follow-Up and Sales Impact tracking continue afterward.",
    difficulty: "foundation",
  },
  {
    id: "q-p6-3",
    pillarId: "p6",
    type: "mcq",
    prompt: "How long after certification does the Manager Follow-Up typically occur?",
    options: ["Immediately", "7 days", "30 days", "1 year"],
    correctAnswer: "30 days",
    explanation: "Managers complete a follow-up roughly 30 days after certification to check whether training is showing up on the floor.",
    difficulty: "intermediate",
  },
  {
    id: "q-p6-4",
    pillarId: "p6",
    type: "ordering",
    prompt: "Put the Sales Impact comparison periods in chronological order.",
    options: ["Before Training", "7 Days", "30 Days", "90 Days"],
    correctAnswer: ["Before Training", "7 Days", "30 Days", "90 Days"],
    explanation: "Sales Impact tracks KPIs at these four checkpoints to measure the durability of behavior change.",
    difficulty: "foundation",
  },
  {
    id: "q-p6-5",
    pillarId: "p6",
    type: "matching",
    prompt: "Match each Kükie Academy module deliverable to what it proves.",
    options: [
      "Knowledge Test = Proves understanding",
      "Practical Assessment = Proves capability",
      "Sales Impact = Proves it stuck",
      "Certificate = Marks the milestone",
    ],
    correctAnswer: [
      "Knowledge Test = Proves understanding",
      "Practical Assessment = Proves capability",
      "Sales Impact = Proves it stuck",
      "Certificate = Marks the milestone",
    ],
    explanation: "Each deliverable answers a different question about whether the training actually worked.",
    difficulty: "advanced",
  },
  {
    id: "q-p6-6",
    pillarId: "p6",
    type: "mcq",
    prompt: "Which of these is NOT one of the 10 KPIs tracked on the Sales Impact dashboard?",
    options: ["Average Transaction Value", "Speed of Service", "Employee's Personal Zodiac Sign", "Beverage Attachment"],
    correctAnswer: "Employee's Personal Zodiac Sign",
    explanation: "Sales Impact tracks operational KPIs like ATV, speed of service, and attachment rates — not irrelevant personal data.",
    difficulty: "foundation",
  },
];

// Deterministic shuffle (same order on server render and client hydration).
const quizRng = new Rng(90210);
export const QUIZ_SET: QuizQuestion[] = quizRng.shuffle(QUESTIONS);
