import type { Slide } from "@/lib/types";

let n = 0;
const idx = () => ++n;

export const SLIDES: Slide[] = [
  {
    id: "s-cover",
    pillarId: null,
    index: idx(),
    type: "cover",
    eyebrow: "Kükie Academy · Module 001",
    title: "Sales Build-Up Excellence",
    subtitle:
      "A complete learning experience for restaurant, café, QSR and hotel teams — built to change behavior, not just deliver a presentation.",
    notes:
      "Welcome the room. Introduce yourself as trainer, set expectations: this is interactive, practical, and tied to real performance metrics they'll see improve over the next 90 days.",
    durationMin: 2,
  },

  // ---------------- PILLAR 1 ----------------
  {
    id: "p1-intro",
    pillarId: "p1",
    index: idx(),
    type: "pillar-intro",
    eyebrow: "Pillar 1 of 6",
    title: "The Science of Restaurant Sales",
    subtitle: "Understanding revenue drivers and the KPIs that move them.",
    notes: "Frame sales as a system, not a personality trait. Everyone in the room can learn it.",
    durationMin: 1,
  },
  {
    id: "p1-s2",
    pillarId: "p1",
    index: idx(),
    type: "concept",
    title: "What Actually Drives Restaurant Revenue",
    bullets: [
      "Revenue is not luck — it's the product of a small number of controllable levers",
      "Guest count: how many people walk through the door or place an order",
      "Average Transaction Value (ATV): how much each guest spends",
      "Frequency: how often guests come back",
      "Your role sits mostly inside ATV — and it's the lever you influence every single shift",
    ],
    notes: "Ask the room: which of these three can a server influence directly, every shift? Land on ATV.",
    durationMin: 3,
  },
  {
    id: "p1-s3",
    pillarId: "p1",
    index: idx(),
    type: "framework",
    title: "The Restaurant Sales Equation",
    framework: {
      name: "Guests × ATV × Frequency = Revenue",
      steps: [
        { title: "Guests", body: "Driven by marketing, location, reputation — largely outside your shift." },
        { title: "ATV", body: "Driven by suggestive selling, upselling, and menu knowledge — this is yours." },
        { title: "Frequency", body: "Driven by the experience you create — guests return when they feel cared for." },
      ],
    },
    notes: "This equation reframes the whole module: we're not teaching 'sales tricks', we're teaching how to move ATV and frequency simultaneously through hospitality.",
    durationMin: 3,
  },
  {
    id: "p1-s4",
    pillarId: "p1",
    index: idx(),
    type: "concept",
    title: "Average Transaction Value (ATV)",
    bullets: [
      "ATV = Total Sales ÷ Number of Transactions",
      "A $1 increase in ATV across 120 covers a day is $120/day — over $43,000/year, per store",
      "ATV moves through three things: what guests order, how much of it, and how premium it is",
      "Every recommendation you make either nudges ATV up or leaves it flat — there's no neutral",
    ],
    notes: "Do the math live on the whiteboard if possible — the annualized number is what makes this land with skeptical staff.",
    durationMin: 3,
  },
  {
    id: "p1-s5",
    pillarId: "p1",
    index: idx(),
    type: "stat",
    title: "Why a Small Lift Matters",
    stat: { value: "+8.4%", label: "average ATV lift", caption: "seen in stores after full Sales Build-Up rollout (Kükie Academy benchmark cohort)" },
    notes: "Set the bar for what 'good' looks like after this training — this is the number Sales Impact will track against.",
    durationMin: 2,
  },
  {
    id: "p1-s6",
    pillarId: "p1",
    index: idx(),
    type: "concept",
    title: "Items Per Transaction (IPT)",
    bullets: [
      "IPT = Total Items Sold ÷ Number of Transactions",
      "The single strongest predictor of ATV in quick-service and casual dining",
      "Every additional relevant item — a side, a drink, a dessert — compounds the check",
      "Target: move IPT by even 0.2 items per guest and the store-wide impact is significant",
    ],
    notes: "Contrast a 'low IPT' order (burger only) with a 'high IPT' order (burger, fries, drink, dessert) taken the same amount of time.",
    durationMin: 3,
  },
  {
    id: "p1-s7",
    pillarId: "p1",
    index: idx(),
    type: "framework",
    title: "Menu Engineering: The Four Quadrants",
    framework: {
      name: "Popularity × Profitability",
      steps: [
        { title: "Stars", body: "High popularity, high profit — always mention these first." },
        { title: "Plow-Horses", body: "High popularity, low profit — pair with a higher-margin add-on." },
        { title: "Puzzles", body: "Low popularity, high profit — these need your recommendation to move." },
        { title: "Dogs", body: "Low popularity, low profit — don't push, but don't discourage either." },
      ],
    },
    notes: "Show the store's actual menu engineering matrix if available. Puzzles are the biggest opportunity — they're profitable but invisible without staff recommending them.",
    durationMin: 4,
  },
  {
    id: "p1-s8",
    pillarId: "p1",
    index: idx(),
    type: "scenario",
    title: "Menu Engineering in Action",
    scenario: {
      setup: "A guest orders the classic burger (a Plow-Horse) and asks 'what do you recommend to go with it?'",
      lines: [
        { speaker: "Guest", text: "What do you recommend to go with it?" },
        { speaker: "Team Member", text: "Our truffle fries are a guest favorite — they pair really well with that burger, and I can add a side of our house sauce if you'd like." },
      ],
    },
    notes: "Truffle fries are a Puzzle — high margin, needs a nudge. This is the recommendation habit we're building all module.",
    durationMin: 3,
  },
  {
    id: "p1-s9",
    pillarId: "p1",
    index: idx(),
    type: "checklist",
    title: "Pillar 1 Recap",
    checklist: {
      dos: [
        "Know your store's ATV and IPT targets",
        "Learn which menu items are Stars, Plow-Horses, Puzzles and Dogs",
        "Think in terms of the full equation: Guests × ATV × Frequency",
      ],
      donts: [
        "Don't treat sales as random or personality-based",
        "Don't recommend the same item to every guest regardless of fit",
      ],
    },
    notes: "Quick knowledge check before moving to Pillar 2 — cold-call one or two trainees on the ATV formula.",
    durationMin: 2,
  },

  // ---------------- PILLAR 2 ----------------
  {
    id: "p2-intro",
    pillarId: "p2",
    index: idx(),
    type: "pillar-intro",
    eyebrow: "Pillar 2 of 6",
    title: "The Psychology of Buying",
    subtitle: "How guests actually make purchasing decisions.",
    notes: "Shift from numbers to the guest's mind. This pillar is the 'why' behind every technique that follows.",
    durationMin: 1,
  },
  {
    id: "p2-s2",
    pillarId: "p2",
    index: idx(),
    type: "framework",
    title: "The Guest Journey Map",
    framework: {
      name: "Arrival → Seated → Ordering → Service → Payment → Departure",
      steps: [
        { title: "Arrival", body: "First impressions set the emotional tone for every decision that follows." },
        { title: "Ordering", body: "The highest-leverage moment for suggestive selling and upselling." },
        { title: "Service", body: "Opportunities for cross-selling appear naturally — refills, courses, check-ins." },
        { title: "Payment & Departure", body: "The moment that decides whether frequency (return visits) goes up or down." },
      ],
    },
    notes: "Ask trainees to identify which stage of the journey they interact with most, and what sales opportunity exists there.",
    durationMin: 3,
  },
  {
    id: "p2-s3",
    pillarId: "p2",
    index: idx(),
    type: "concept",
    title: "Guest Psychology 101",
    bullets: [
      "Guests rarely make a fully rational decision — they decide fast and justify later",
      "Decision fatigue: too many options creates hesitation, not excitement",
      "A confident, specific recommendation reduces guest effort and increases satisfaction",
      "Guests want to be guided, not sold to — the framing of the offer matters more than the offer itself",
    ],
    notes: "This is the psychological foundation for suggestive selling in Pillar 4 — plant the seed here.",
    durationMin: 3,
  },
  {
    id: "p2-s4",
    pillarId: "p2",
    index: idx(),
    type: "concept",
    title: "Anchoring & the Power of the First Suggestion",
    bullets: [
      "The first option mentioned becomes the mental 'anchor' guests compare everything else to",
      "Leading with a premium or well-paired item raises the perceived baseline",
      "Example: mentioning the large size first makes the medium feel like the 'safe middle ground'",
      "This is not manipulation — it only works when the anchor is genuinely a great option",
    ],
    notes: "Emphasize the ethics angle — anchoring works long-term only when paired with honesty about what's actually good.",
    durationMin: 3,
  },
  {
    id: "p2-s5",
    pillarId: "p2",
    index: idx(),
    type: "concept",
    title: "Social Proof & Scarcity, Used Honestly",
    bullets: [
      "'This is one of our most-loved dishes' works because it's true and it's specific",
      "'We only have a few of the seasonal special left today' creates real urgency when accurate",
      "Never fabricate scarcity or popularity — guests can tell, and it damages trust fast",
      "Genuine enthusiasm from the team member is the strongest social proof of all",
    ],
    notes: "This slide sets the ethical guardrails for the persuasion techniques in the rest of the module.",
    durationMin: 3,
  },
  {
    id: "p2-s6",
    pillarId: "p2",
    index: idx(),
    type: "scenario",
    title: "Reading the Table",
    scenario: {
      setup: "A family of four sits down. Two kids, two adults. One adult is scanning the menu quickly, the other is relaxed and chatting.",
      lines: [
        { speaker: "Team Member (internal read)", text: "Quick scanner = time-pressured, wants an efficient recommendation. Relaxed guest = open to a fuller experience." },
        { speaker: "Team Member", text: "Happy to help you move quickly if you're on a schedule — our lunch combo comes out fast and includes a drink. Or if you've got time, I'd love to walk you through today's specials." },
      ],
    },
    notes: "This is about observation, not scripts. Ask trainees what other cues (business attire, celebration, first-time visit) change the read.",
    durationMin: 3,
  },
  {
    id: "p2-s7",
    pillarId: "p2",
    index: idx(),
    type: "concept",
    title: "Building Guest Connections",
    bullets: [
      "A 15-second genuine connection outperforms a 60-second scripted pitch",
      "Use the guest's name, reference something they said, remember returning guests",
      "Connection lowers guest resistance to any recommendation that follows",
      "This is hospitality doing the selling — covered fully in Pillar 3",
    ],
    notes: "Bridge slide into Pillar 3.",
    durationMin: 2,
  },
  {
    id: "p2-s8",
    pillarId: "p2",
    index: idx(),
    type: "stat",
    title: "The Connection Effect",
    stat: { value: "23%", label: "higher check average", caption: "from guests who report a genuine connection with their server (Kükie Academy guest survey data)" },
    notes: "This number bridges psychology directly back into the revenue conversation from Pillar 1.",
    durationMin: 2,
  },
  {
    id: "p2-s9",
    pillarId: "p2",
    index: idx(),
    type: "checklist",
    title: "Pillar 2 Recap",
    checklist: {
      dos: [
        "Read the table before you speak — pace, occasion, party size",
        "Lead with your best honest recommendation to set a strong anchor",
        "Use real social proof and real scarcity only",
      ],
      donts: [
        "Don't recite a script that ignores what the guest is telling you",
        "Don't exaggerate popularity or availability",
      ],
    },
    notes: "Transition: 'Now that we understand how guests decide, let's talk about how service itself becomes the sale.'",
    durationMin: 2,
  },

  // ---------------- PILLAR 3 ----------------
  {
    id: "p3-intro",
    pillarId: "p3",
    index: idx(),
    type: "pillar-intro",
    eyebrow: "Pillar 3 of 6",
    title: "Sales Through Hospitality",
    subtitle: "Using genuine service to create natural sales moments.",
    notes: "Core message: the best sales technique is excellent hospitality delivered with intent.",
    durationMin: 1,
  },
  {
    id: "p3-s2",
    pillarId: "p3",
    index: idx(),
    type: "concept",
    title: "Hospitality Is the Sale",
    bullets: [
      "A recommendation delivered with care is hospitality — the same words delivered flatly feel like a pitch",
      "Guests can't tell the difference between 'upselling' and 'taking great care of them' when it's done right",
      "Your tone, pace and eye contact carry more weight than your word choice",
      "The goal is never to sell something a guest doesn't want — it's to make sure they don't miss something they would have loved",
    ],
    notes: "This reframes the entire module for skeptical staff who associate 'sales' with being pushy.",
    durationMin: 3,
  },
  {
    id: "p3-s3",
    pillarId: "p3",
    index: idx(),
    type: "concept",
    title: "The Language of Suggestion vs. the Language of the Order-Taker",
    bullets: [
      "Order-taker: 'Anything else?' — passive, easy to decline, no information",
      "Suggester: 'Our warm chocolate lava cake is made fresh — would you like me to bring one out for the table?' — specific, sensory, easy to say yes to",
      "Small language shifts create measurably different outcomes",
      "This is a habit you build one shift at a time, not an overnight switch",
    ],
    notes: "Have trainees rewrite 'anything else?' three different ways as a quick pair exercise.",
    durationMin: 3,
  },
  {
    id: "p3-s4",
    pillarId: "p3",
    index: idx(),
    type: "framework",
    title: "Handling Objections: The 4 A's",
    framework: {
      name: "Acknowledge → Ask → Advise → Affirm",
      steps: [
        { title: "Acknowledge", body: "Validate the guest's concern without arguing — 'Totally understand.'" },
        { title: "Ask", body: "Get more information — 'Are you looking for something lighter, or watching the budget?'" },
        { title: "Advise", body: "Offer a genuinely fitting alternative based on what you learned." },
        { title: "Affirm", body: "Confirm the choice positively — 'Great pick, that's one of my favorites.'" },
      ],
    },
    notes: "This framework is used directly in the Practical Assessment and Role Play sections — make sure it's memorized.",
    durationMin: 4,
  },
  {
    id: "p3-s5",
    pillarId: "p3",
    index: idx(),
    type: "scenario",
    title: "Objection Scenario: 'It's Too Expensive'",
    scenario: {
      setup: "A guest hesitates on the recommended premium burger and says it feels pricey.",
      lines: [
        { speaker: "Guest", text: "That one's a bit pricey for me." },
        { speaker: "Team Member", text: "Totally understand — are you looking for something similar but a bit lighter on the wallet, or more in the mood for something smaller overall?" },
        { speaker: "Guest", text: "Something similar, just less expensive." },
        { speaker: "Team Member", text: "Our classic burger has the same house-made patty, just without the truffle aioli and brie — still one of our most-loved dishes." },
      ],
    },
    notes: "Point out: no pressure, no discounting, just a genuine alternative found through a question.",
    durationMin: 3,
  },
  {
    id: "p3-s6",
    pillarId: "p3",
    index: idx(),
    type: "scenario",
    title: "Objection Scenario: 'I'm Not That Hungry'",
    scenario: {
      setup: "A guest declines a starter, saying they don't have much of an appetite today.",
      lines: [
        { speaker: "Guest", text: "I'm not that hungry, I'll just do the main." },
        { speaker: "Team Member", text: "No problem at all — if you change your mind, our soup of the day is light and comes out fast, happy to add it anytime before your main arrives." },
      ],
    },
    notes: "This is a soft, no-pressure offer that leaves the door open — often guests say yes a few minutes later.",
    durationMin: 3,
  },
  {
    id: "p3-s7",
    pillarId: "p3",
    index: idx(),
    type: "checklist",
    title: "Pillar 3 Recap",
    checklist: {
      dos: [
        "Use the 4 A's every time you hear hesitation",
        "Replace 'anything else?' with a specific, sensory suggestion",
        "Deliver every recommendation with genuine warmth",
      ],
      donts: [
        "Don't argue with an objection or use pressure",
        "Don't discount instead of understanding the real concern",
      ],
    },
    notes: "Transition into Pillar 4: 'Now let's get specific about the techniques themselves.'",
    durationMin: 2,
  },

  // ---------------- PILLAR 4 ----------------
  {
    id: "p4-intro",
    pillarId: "p4",
    index: idx(),
    type: "pillar-intro",
    eyebrow: "Pillar 4 of 6",
    title: "Advanced Selling Techniques",
    subtitle: "Upselling, cross-selling, premium selling and attachment strategies.",
    notes: "This is the most tactical pillar — trainees should leave with scripts they can use on their very next shift.",
    durationMin: 1,
  },
  {
    id: "p4-s2",
    pillarId: "p4",
    index: idx(),
    type: "concept",
    title: "Suggestive Selling, Defined",
    bullets: [
      "Offering an item the guest hadn't thought to order — appetizer, drink, side",
      "Works best in the first 90 seconds after the order is taken, before the kitchen fires it",
      "Effective suggestive selling is specific: name the dish, describe it briefly, make it easy to say yes",
      "This is the foundation technique — everything else in this pillar builds on it",
    ],
    notes: "Contrast a vague ('would you like an appetizer?') with a specific suggestion.",
    durationMin: 3,
  },
  {
    id: "p4-s3",
    pillarId: "p4",
    index: idx(),
    type: "framework",
    title: "Suggestive Selling Scripts",
    framework: {
      name: "Name → Describe → Invite",
      steps: [
        { title: "Name", body: "'Our truffle fries...' — be specific, never generic." },
        { title: "Describe", body: "'...are hand-cut and tossed with parmesan and truffle oil...' — one sensory detail." },
        { title: "Invite", body: "'...would you like me to add an order for the table?' — direct, easy yes." },
      ],
    },
    notes: "Have trainees build their own Name → Describe → Invite script for one item on their actual menu, right now.",
    durationMin: 4,
  },
  {
    id: "p4-s4",
    pillarId: "p4",
    index: idx(),
    type: "concept",
    title: "Upselling",
    bullets: [
      "Guiding a guest toward a larger, better, or more premium version of what they already chose",
      "Example: 'For just $2 more you can upgrade to the ribeye instead of the sirloin — it's noticeably more tender'",
      "Works because the guest has already committed to the category — you're refining, not redirecting",
      "Always frame in terms of the guest's benefit, not just the price difference",
    ],
    notes: "Emphasize: upselling is a refinement of a decision already made, which makes it low-friction.",
    durationMin: 3,
  },
  {
    id: "p4-s5",
    pillarId: "p4",
    index: idx(),
    type: "concept",
    title: "Cross-Selling",
    bullets: [
      "Recommending a complementary item from a different category — a drink with a meal, a sauce with fries",
      "The strongest cross-sell moments are pairing-based: 'this wine pairs beautifully with that dish'",
      "Cross-selling is where IPT (items per transaction) is won or lost",
      "Timing matters — cross-sell at order time, not after the food has already arrived",
    ],
    notes: "This is the direct lever on IPT introduced back in Pillar 1 — make the callback explicit.",
    durationMin: 3,
  },
  {
    id: "p4-s6",
    pillarId: "p4",
    index: idx(),
    type: "concept",
    title: "Premium Selling",
    bullets: [
      "Leading with the best version of an experience, not the cheapest",
      "Guests often don't know the premium option exists unless it's offered first",
      "Premium selling only works when the item genuinely delivers — never oversell quality that isn't there",
      "Pairs directly with anchoring from Pillar 2: lead with premium, let guests choose their comfort level",
    ],
    notes: "This is the most advanced technique — reserve extra practice time in Role Play for this one.",
    durationMin: 3,
  },
  {
    id: "p4-s7",
    pillarId: "p4",
    index: idx(),
    type: "concept",
    title: "Attachment Strategies: Beverage & Dessert",
    bullets: [
      "Beverage attachment: suggesting a drink pairing at the moment the order is taken, not after",
      "Dessert attachment: planting the seed early — 'save room, our dessert menu is worth it' — then following up",
      "Combo rate: bundling item + side + drink as a single easy decision instead of three separate ones",
      "These three metrics are tracked live in the Sales Impact dashboard after this training",
    ],
    notes: "Direct callback to the Sales Impact section trainees will see in their own performance data.",
    durationMin: 3,
  },
  {
    id: "p4-s8",
    pillarId: "p4",
    index: idx(),
    type: "stat",
    title: "The Compounding Effect of Attachment",
    stat: { value: "+$2.10", label: "average check lift per transaction", caption: "when beverage, dessert, and combo attachment are all applied consistently" },
    notes: "Multiply by covers per shift to show the real earning/tip impact for the team member personally.",
    durationMin: 2,
  },
  {
    id: "p4-s9",
    pillarId: "p4",
    index: idx(),
    type: "scenario",
    title: "Full Technique Stack in One Interaction",
    scenario: {
      setup: "A guest orders a classic burger with no sides.",
      lines: [
        { speaker: "Guest", text: "I'll just get the classic burger." },
        { speaker: "Team Member", text: "Great choice — our truffle fries pair really well with that if you'd like to add them. And can I start you with a drink — we've got a house-made lemonade that's a guest favorite." },
        { speaker: "Guest", text: "Sure, sounds good." },
        { speaker: "Team Member", text: "Perfect — and if you've got room later, save space for our chocolate lava cake, I'll check back in before the kitchen closes dessert orders." },
      ],
    },
    notes: "This single exchange demonstrates suggestive selling, cross-selling and dessert attachment in under 20 seconds.",
    durationMin: 3,
  },
  {
    id: "p4-s10",
    pillarId: "p4",
    index: idx(),
    type: "checklist",
    title: "Pillar 4 Recap",
    checklist: {
      dos: [
        "Use Name → Describe → Invite for every suggestive sell",
        "Upsell by refining a decision already made",
        "Attach a beverage at order time, plant the dessert seed early",
      ],
      donts: [
        "Don't stack more than 2-3 suggestions in one breath — it overwhelms",
        "Don't oversell an item that won't deliver on the description",
      ],
    },
    notes: "Transition into Pillar 5: 'Now let's talk about how this gets executed and coached on the floor, every single shift.'",
    durationMin: 2,
  },

  // ---------------- PILLAR 5 ----------------
  {
    id: "p5-intro",
    pillarId: "p5",
    index: idx(),
    type: "pillar-intro",
    eyebrow: "Pillar 5 of 6",
    title: "Operational Execution",
    subtitle: "Coaching, role plays and daily floor routines.",
    notes: "This pillar is about turning knowledge into habit through repetition and coaching structure.",
    durationMin: 1,
  },
  {
    id: "p5-s2",
    pillarId: "p5",
    index: idx(),
    type: "framework",
    title: "The Daily Floor Routine",
    framework: {
      name: "Huddle → Execute → Debrief",
      steps: [
        { title: "Pre-Shift Huddle", body: "2 minutes: today's Star/Puzzle items, one technique focus for the shift." },
        { title: "Peak Execution", body: "Apply the technique focus consistently — managers spot-check and coach in real time." },
        { title: "Post-Shift Debrief", body: "What worked, what didn't, one thing to try differently tomorrow." },
      ],
    },
    notes: "This routine is what sustains the training beyond today — it belongs to managers and shift leads.",
    durationMin: 3,
  },
  {
    id: "p5-s3",
    pillarId: "p5",
    index: idx(),
    type: "concept",
    title: "Coaching in the Moment",
    bullets: [
      "The best coaching happens within minutes of the interaction, not days later in a review",
      "Catch people doing it right — specific praise builds the habit faster than correction alone",
      "When correcting, use the 4 A's structure: it works for coaching conversations too",
      "Every practical assessment in this module doubles as a coaching conversation, not just a score",
    ],
    notes: "This sets up trainers and managers for the Practical Assessment and Manager Follow-Up sections.",
    durationMin: 3,
  },
  {
    id: "p5-s4",
    pillarId: "p5",
    index: idx(),
    type: "scenario",
    title: "Role Play Walkthrough: Guest Orders a Burger",
    scenario: {
      setup: "This is the exact scenario trainees will perform live in the Role Play module — Guest orders, Team Member recommends, Guest objects, Team Member resolves.",
      lines: [
        { speaker: "Guest", text: "I'll have the classic burger, please." },
        { speaker: "Team Member", text: "Great choice — can I tempt you with our truffle fries and a drink to go with that?" },
        { speaker: "Guest", text: "I'm okay, just the burger." },
        { speaker: "Team Member", text: "No problem at all — I'll get that started for you right away." },
      ],
    },
    notes: "Point out: even a 'no' is handled gracefully, with zero pressure — that's a pass, not a fail, if delivered warmly.",
    durationMin: 3,
  },
  {
    id: "p5-s5",
    pillarId: "p5",
    index: idx(),
    type: "concept",
    title: "Practical Assessment: What Gets Scored",
    bullets: [
      "Greeting, smile, eye contact — the hospitality fundamentals from Pillar 3",
      "Menu knowledge and confidence — how well the techniques from Pillar 4 are internalized",
      "Upselling, cross-selling and closing — the applied sales behaviors",
      "Guest engagement, professionalism, and overall impression",
    ],
    notes: "Preview the exact rubric trainees will be scored against in the Practical Assessment module — no surprises.",
    durationMin: 3,
  },
  {
    id: "p5-s6",
    pillarId: "p5",
    index: idx(),
    type: "checklist",
    title: "Pillar 5 Recap",
    checklist: {
      dos: [
        "Run the Huddle → Execute → Debrief routine every shift",
        "Coach in the moment, praise specifically",
        "Know the Practical Assessment rubric before you're scored on it",
      ],
      donts: [
        "Don't save all feedback for a formal review days later",
        "Don't treat role play as a formality — it's the closest thing to the real floor",
      ],
    },
    notes: "Transition into Pillar 6: 'Finally — how do we know all of this actually worked?'",
    durationMin: 2,
  },

  // ---------------- PILLAR 6 ----------------
  {
    id: "p6-intro",
    pillarId: "p6",
    index: idx(),
    type: "pillar-intro",
    eyebrow: "Pillar 6 of 6",
    title: "Measuring Success",
    subtitle: "Dashboards, KPI tracking and post-training performance.",
    notes: "This is what makes Kükie Academy a performance platform, not just a course — the training doesn't end when the slides do.",
    durationMin: 1,
  },
  {
    id: "p6-s2",
    pillarId: "p6",
    index: idx(),
    type: "concept",
    title: "What Gets Measured Gets Managed",
    bullets: [
      "Every module in Kükie Academy connects to a real operational KPI, not just a quiz score",
      "Knowledge Test proves understanding; Practical Assessment proves capability; Sales Impact proves it stuck",
      "Managers and trainers see this data in real time on the Store and Regional dashboards",
      "Executives see aggregate training ROI on the Executive dashboard",
    ],
    notes: "This is the pitch for why this training is different from a one-time workshop.",
    durationMin: 3,
  },
  {
    id: "p6-s3",
    pillarId: "p6",
    index: idx(),
    type: "concept",
    title: "The Knowledge Test",
    bullets: [
      "Covers all six pillars with multiple question formats",
      "Pass mark: 80%",
      "Immediate feedback on every question, with explanations",
      "A strong score here predicts — but doesn't guarantee — strong practical performance",
    ],
    notes: "Set expectations for the assessment immediately following the presentation.",
    durationMin: 2,
  },
  {
    id: "p6-s4",
    pillarId: "p6",
    index: idx(),
    type: "concept",
    title: "Certification & Manager Follow-Up",
    bullets: [
      "Passing both the Knowledge Test and Practical Assessment earns the Kükie Academy certificate",
      "30 days later, managers complete a short follow-up: is the training showing up on the floor?",
      "This follow-up feeds directly into promotion readiness and coaching plans",
      "Certification is a milestone, not a finish line",
    ],
    notes: "This slide sets up the Manager Follow-Up module trainees will encounter a month from now.",
    durationMin: 3,
  },
  {
    id: "p6-s5",
    pillarId: "p6",
    index: idx(),
    type: "stat",
    title: "Sales Impact: What We Track",
    stat: { value: "10 KPIs", label: "before vs. 7 / 30 / 90 days", caption: "ATV, guest count, IPT, beverage & dessert attachment, combo rate, sales growth, CSAT, speed of service, and individual sales ranking" },
    notes: "Preview the Sales Impact dashboard — this is the proof point that ties the whole module together.",
    durationMin: 3,
  },
  {
    id: "p6-s6",
    pillarId: "p6",
    index: idx(),
    type: "checklist",
    title: "Pillar 6 Recap",
    checklist: {
      dos: [
        "Treat the Knowledge Test and Practical Assessment as connected, not separate hurdles",
        "Expect a manager check-in 30 days after certification",
        "Track your own numbers on the Sales Impact dashboard",
      ],
      donts: [
        "Don't view certification as the end of the learning journey",
        "Don't ignore the post-training follow-up — it's where habits get locked in",
      ],
    },
    notes: "Final recap before closing.",
    durationMin: 2,
  },

  {
    id: "s-closing",
    pillarId: null,
    index: idx(),
    type: "closing",
    title: "You're Ready to Build Up the Sale",
    subtitle:
      "Next: complete your Digital Workbook, sit the Knowledge Test, and schedule your Practical Assessment and Role Play with your trainer.",
    notes: "Close with energy. Remind the room this is Module 001 of the full Kükie Academy — the same framework will show up again in every future module.",
    durationMin: 2,
  },
];

export const TOTAL_SLIDE_MINUTES = SLIDES.reduce((s, sl) => s + sl.durationMin, 0);
